import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Turnstile Next.js Example</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<main>
				<section className='py-16'>
					<h1 className='text-4xl text-center text-slate-700 font-bold tracking-normal'>
						 Turnstile example
					</h1>
				</section>
			</main>
		</>
	);
}
