import ContactForm from '@/components/ContactForm';
import ContactFormProvider from '@/context/ContactFormProvider';
import Head from 'next/head';

export default function Home() {
	return (
		<ContactFormProvider>
			<>
				<Head>
					<title>Turnstile Next.js Example | Contact Form</title>
					<meta
						name='description'
						content='Generated by create next app'
					/>
					<meta
						name='viewport'
						content='width=device-width, initial-scale=1'
					/>
					<link
						rel='icon'
						href='/favicon.ico'
					/>
				</Head>
				<main className='bg-primary min-h-screen'>
					<section className='py-12'>
						<ContactForm />
					</section>
				</main>
			</>
		</ContactFormProvider>
	);
}
